import { Bookmark, BookMarked, CheckSquare, Pause, Play, Plus, RotateCcw, Search, Square, Timer, Trash2, Type, type LucideIcon } from "lucide-react";
import { useState } from "react";
import type { MobileTool } from "../mobileModel";
import type { MobileLesson } from "../mobileModel";
import type { TodoItem } from "../../../lib/persistence";
import type { MobileTimerReading } from "../../../lib/mobileTimer";
import type { MobileDictionaryService } from "../../../lib/mobileDictionaryService";
import type { DictionaryEntry } from "../../../types/dictionary";
import type { SavedVocabularyItem } from "../../../lib/mobileCourseState";
import { MobileDictionaryPanel } from "./MobileDictionaryPanel";

const tools: { id: MobileTool; label: string; icon: LucideIcon }[] = [{ id: "timer", label: "Study Timer", icon: Timer }, { id: "todos", label: "Todos", icon: CheckSquare }, { id: "bookmarks", label: "Bookmarks", icon: Bookmark }, { id: "dictionary", label: "Dictionary", icon: Search }, { id: "vocabulary", label: "Vocabulary", icon: BookMarked }];

export function MobileTools({ active, onActive, timer, timerMode, timerPreset, onTimer, onTimerReset, todos, onTodo, onAddTodo, bookmarks, onBookmark, storage, onEnableCourseSaving, dictionaryService, vocabulary, onAddVocabulary, onRemoveVocabulary }: { active: MobileTool; onActive: (tool: MobileTool) => void; timer: MobileTimerReading; timerMode: "focus" | "stopwatch"; timerPreset: number; onTimer: () => void; onTimerReset: () => void; todos: TodoItem[]; onTodo: (id: string) => void; onAddTodo: (label: string) => void; bookmarks: MobileLesson[]; onBookmark: (id: string) => void; storage: "portable" | "localOnly"; onEnableCourseSaving: () => void; dictionaryService: MobileDictionaryService; vocabulary: SavedVocabularyItem[]; onAddVocabulary: (entry: DictionaryEntry) => void; onRemoveVocabulary: (id: string) => void }) {
  const current = tools.find((item) => item.id === active)!;
  return <div className="m-screen m-tools"><header className="m-page-header"><span className="m-eyebrow">Study kit</span><h2>Tools</h2><p>Focused utilities for the lesson you are studying.</p>{storage === "localOnly" ? <><span className="m-state-location">Saved on this device</span><button type="button" className="m-secondary" onClick={onEnableCourseSaving}>Enable course saving</button></> : null}</header><div className="m-tools-layout"><nav className="m-tool-tabs" aria-label="Tools"><div className="m-tool-grid">{tools.map(({ id, label, icon: Icon }) => <button type="button" key={id} aria-label={label} aria-current={active === id ? "page" : undefined} onClick={() => onActive(id)}><Icon /><span>{label}</span></button>)}</div></nav><main className="m-tool-detail"><span className="m-eyebrow">Current tool</span><h3>{current.label}</h3>{active === "timer" ? <TimerPanel reading={timer} mode={timerMode} preset={timerPreset} onToggle={onTimer} onReset={onTimerReset} /> : null}{active === "todos" ? <TodoPanel todos={todos} onTodo={onTodo} onAdd={onAddTodo} /> : null}{active === "bookmarks" ? <BookmarkPanel items={bookmarks} onOpen={onBookmark} /> : null}{active === "dictionary" ? <MobileDictionaryPanel service={dictionaryService} onAddVocabulary={onAddVocabulary} /> : null}{active === "vocabulary" ? <VocabularyPanel items={vocabulary} onRemove={onRemoveVocabulary} /> : null}</main></div></div>;
}

function TimerPanel({ reading, mode, preset, onToggle, onReset }: { reading: MobileTimerReading; mode: "focus" | "stopwatch"; preset: number; onToggle: () => void; onReset: () => void }) { const shown = mode === "focus" ? reading.remainingSeconds : reading.elapsedSeconds; const minutes = String(Math.floor(shown / 60)).padStart(2, "0"); const seconds = String(shown % 60).padStart(2, "0"); const running = reading.phase === "running"; return <div className="m-timer"><div className="m-timer-ring"><span>{mode === "focus" ? "FOCUS" : "STOPWATCH"}</span><strong>{minutes}:{seconds}</strong><small>{reading.phase === "completed" ? "Session complete" : running ? "Session in progress" : "Ready when you are"}</small></div><div><button className="m-primary" type="button" disabled={reading.phase === "completed"} onClick={onToggle}>{running ? <Pause fill="currentColor" /> : <Play fill="currentColor" />} {running ? "Pause" : `Start ${preset}m focus`}</button><button className="m-icon-button" type="button" aria-label="Reset timer" onClick={onReset}><RotateCcw /></button></div><p>Timer state is kept on this device and survives navigation and restart.</p></div>; }
function TodoPanel({ todos, onTodo, onAdd }: { todos: TodoItem[]; onTodo: (id: string) => void; onAdd: (label: string) => void }) { const [label, setLabel] = useState(""); return <><form className="m-tool-create" onSubmit={(event) => { event.preventDefault(); if (label.trim()) { onAdd(label); setLabel(""); } }}><input aria-label="New todo" value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Add a study todo" /><button type="submit" aria-label="Add todo"><Plus /></button></form><div className="m-tool-list">{todos.length ? todos.map((todo) => <button type="button" key={todo.id} onClick={() => onTodo(todo.id)} className={todo.done ? "is-done" : ""}>{todo.done ? <CheckSquare /> : <Square />}<span>{todo.label}</span></button>) : <p className="m-tool-intro">No todos yet.</p>}</div></>; }
function BookmarkPanel({ items, onOpen }: { items: MobileLesson[]; onOpen: (id: string) => void }) { return <><p className="m-tool-intro">Saved lessons</p><div className="m-tool-list">{items.map((item) => <button type="button" key={item.id} aria-label={`Open bookmarked lesson ${item.name.replace(/\.[^.]+$/, "")}`} onClick={() => onOpen(item.id)}><Bookmark /><span>{item.name.replace(/\.[^.]+$/, "")}</span></button>)}</div></>; }
function VocabularyPanel({ items, onRemove }: { items: SavedVocabularyItem[]; onRemove: (id: string) => void }) { return <div className="m-tool-list">{items.length ? items.map((item) => <div key={item.id}><Type /><span><strong>{item.headword}</strong><small>{item.shortDefinition}</small></span><button type="button" aria-label={`Remove ${item.headword} from Vocabulary`} onClick={() => onRemove(item.id)}><Trash2 /></button></div>) : <p className="m-tool-intro">No saved vocabulary yet.</p>}</div>; }
